version: "3.8"

services:
  vote:
    build: ./vote
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: "redis"
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_RUN_PORT: "8080"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: always
